name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
      - 'chore'
  default: patch
template: |
  __Compatibility__

  * Requires Deno v<DENO_VERSION> or higher
  * Uses Deno std@<STD_VERSION>

  or

  * Uses Node version 12 or higher

  __Importing__

  * Import this latest release by using the following in your project(s):
    ```typescript
    import { contextFinder } from "https://deno.land/x/context_finder@v$RESOLVED_VERSION/mod.ts";
    ```

    Or update the npm module:
    ```
    npm update context-finder
    ```

  __Updates__

  $CHANGES