language: node_js

before_install:
  - pip install --user codecov > /dev/null

after_success:
  - codecov --file coverage/lcov.info --disable search

install:
  - npm install -g codecov
  - npm install -g nyc

script:
  - nyc cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - npm run build
  - npm run test
  - codecov