language: node_js

#before_install:
#  - pip install --user codecov > /dev/null

#after_success:
  #- codecov --file coverage/lcov.info --disable search

install:
  - npm install -g codecov
  - npm install -g nyc

script:
  - npm run build
  #- nyc cover ./node_modules/.bin/mocha --reporter lcovonly -- -R spec
  - npm run test
  #- codecov