name: master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Deno Tests
        run: |
          deno test -A --coverage=cov tests
          deno coverage --lcov cov --exclude=tests > cov.lcov
      
      - name: Upload Coverage
        uses: codecov/codecov-action@v2.1.0
        with:
          name: dami
          files: cov.lcov

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - run: deno lint
      - run: deno fmt --check
