name: master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master

      - name: Deno Tests
        run: |
          deno test -A tests/deno

      - name: Node Tests
        run: |
          npm run build
          npm run test

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@master
      - run: deno lint --unstable --ignore=node_modules,tests/node,index.ts,dist,src/node/context-finder.ts
      - run: deno fmt --check --ignore=node_modules,tests/node,index.ts,dist